### PR TITLE
Properly propagate root cause of exception in PipelineParser

### LINKED ISSUE #24: Pipeline as YAML Parser classes do not propagate exception causes
**Describe the bug**
Pipeline as YAML parsers do not retain the cause exceptions. In such case, some diagnostics info may be lost. It may become harder to users to diagnose the failure causes.

Sample code:

```
        catch (Exception e) {
            throw new PipelineAsYamlRuntimeException(e.getLocalizedMessage());
        }
```

Sample error from Jenkinsfile Runner:

```
[2020-07-17T20:27:45.806Z] 2020-07-17 20:27:45.752+0000 [id=112]	WARNING	i.j.j.runner.JenkinsEmbedder#before: Jenkins.theInstance was not cleared by a previous test, doing that now

[2020-07-17T20:27:46.618Z] 2020-07-17 20:27:46.513+0000 [id=133]	WARNING	o.j.p.w.flow.FlowExecutionList#unregister: Owner[job/1:job #1] was not in the list to begin with: []

[2020-07-17T20:27:46.618Z] Started

[2020-07-17T20:27:46.618Z] org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.exceptions.PipelineAsYamlRuntimeException: java.util.ArrayList cannot be cast to java.lang.String

[2020-07-17T20:27:46.618Z] 	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.parsers.PipelineParser.parse(PipelineParser.java:53)

[2020-07-17T20:27:46.618Z] 	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.cps.PipelineCpsScmFlowDefinition.create(PipelineCpsScmFlowDefinition.java:50)

[2020-07-17T20:27:46.618Z] 	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.PipelineAsYamlScmFlowDefinition.create(PipelineAsYamlScmFlowDefinition.java:74)

[2020-07-17T20:27:46.618Z] 	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)

[2020-07-17T20:27:46.618Z] 	at hudson.model.ResourceController.execute(ResourceController.java:97)

[2020-07-17T20:27:46.618Z] 	at hudson.model.Executor.run(Executor.java:428)

[2020-07-17T20:27:46.618Z] Finished: FAILURE
```

**To Reproduce**

See the test in https://github.com/jenkinsci/jenkinsfile-runner/pull/316

**Expected behavior**
All exceptions are properly propagated

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Fixes #24 . I suspect that `PipelineAsYamlRuntimeException` may also need an update later

### CODE REVIEW

File: src/main/java/org/jenkinsci/plugins/workflow/multibranch/yaml/pipeline/exceptions/PipelineAsYamlRuntimeException.java [hunk 1]
```diff
@@ -16,4 +16,9 @@ public PipelineAsYamlRuntimeException(String s) {
         super(s);
         LOGGER.log(Level.FINE, s, this);
     }
+
+    public PipelineAsYamlRuntimeException(String message, Throwable cause) {
+        super(message, cause);
+        LOGGER.log(Level.FINE, s, this);
```
Comment (oleg-nenashev) [inline src/main/java/org/jenkinsci/plugins/workflow/multibranch/yaml/pipeline/exceptions/PipelineAsYamlRuntimeException.java:22]:
```suggestion
        LOGGER.log(Level.FINE, message, this);
```
